### PR TITLE
Wrong coverage for await foreach with generic method

### LINKED ISSUE #1210: Wrong coverage for "await foreach" when method is generic
I'm using coverlet.msbuild v3.1.0 (and tried also with the current nightly build) and there is an uncovered statement reported.
image

I tried to reproduce it but I didn't managed to get an reproduction.
Any ideas what the problem could be and how I can provide an reproduction?

```csharp
public class AsyncForeachReproduction
{
    private static async IAsyncEnumerable<int> RangeAsync(int start, int count)
    {
        for (int i = 0; i < count; i++)
        {
            await Task.Delay(i);
            yield return start + i;
        }
    }

    public async Task Execute()
    {
        await foreach (var a in RangeAsync(1, 5))
        {
            Console.WriteLine(a);
            await Task.CompletedTask;
        }

        await Task.CompletedTask;
    }
}
```

### PR DESCRIPTION
**Pull request by daveMueller**
closes #1210 

grafik

### CODE REVIEW

**Comment by daveMueller** [comment]
@MarcoRossignoli Can you run the build again? The failed test has nothing to do with my changes. The job already was green before I updated the changelog.

**Review by MarcoRossignoli — APPROVED** [review]
Thanks a lot ❤️

**Comment by daveMueller** [comment]
What I've analysed is that in the case of generics, the operand isn't a `FieldDefinition`. So every symbol check that is looking for a `FieldDefinition` will not match. There are places in `CecilSymbolHelper` where this is already considered, e.g. [https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.core/Symbols/CecilSymbolHelper.cs#L114-L115](https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.core/Symbols/CecilSymbolHelper.cs#L114-L115).But there are also a couple of places where it isn't. 
In this PR I only changed the necessary places to fix the bug but maybe it would make sense to change this everywhere in `CecilSymbolHelper`?

**Comment by MarcoRossignoli** [comment]
I think it's ok as-is for now, if we don't have feedback.
If you feel safe to update also around go for it.

**Pull request merged**
