### PR TITLE
Put AppContext.OnProcessExit body inside a try/finally

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
fixes https://github.com/coverlet-coverage/coverlet/issues/1287

image

cc: @ViktorHofer @stephentoub @jkotas

### CODE REVIEW

**Comment by stephentoub** [comment]
Thank you for fixing it.

**Comment by stephentoub** [comment]
When do we expect a new official nuget release with the corelib-related fixes to published?

**Comment by MarcoRossignoli** [comment]
I'd like a test before release a new version, to be sure that is working as expected...is it possible that someone with more "knowledge" and a ready runtime env give it a try with the dogfood?
I'm a bit rusty with the new layout/build of runtime repo.

**Comment by stephentoub** [comment]
> I'd like a test before release a new version, to be sure that is working as expected...is it possible that someone with more "knowledge" and a ready runtime env give it a try with the dogfood?

Sure, I can try on Monday.

**Comment by stephentoub** [comment]
Is the code you're generating actually what's shown in the image above?  return'ing out of a finally is invalid.

**Comment by MarcoRossignoli** [comment]
I've fixed...pair of issues, missing end finally and patch every return. Looks like ILSpy validation is not complete, sometimes it gives errors...not this time. Too much time far from IL generation 🙂

Also we don't have specific tests for the corelib custom case, it doesn't help.

**Pull request merged**
