### PR TITLE
Handle PDB location when project build externally

### PR DESCRIPTION
**Pull request by mklemarczyk**
The PR is to handle discovery of PDB files for project build externally (Cloud build, Cluster build, Remote build).
Therefore the path mostly will not match with original build location and the PDB file should be detected by looking in the same directory as module file.

The issue is reproduced with new unit test.

The PR solves the issue #1353

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/coverlet-coverage/coverlet?pullRequest=1354) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/coverlet-coverage/coverlet?pullRequest=1354) before we can accept your contribution.<br/><br/>:x: mklemarczyk [sign now](https://cla.dotnetfoundation.org/coverlet-coverage/coverlet?pullRequest=1354)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/coverlet-coverage/coverlet?pullRequest=1354) it.</sub>

**Comment by mklemarczyk** [comment]
It is due to mixed paths (windows + linux).

The tests for linux and ios will need to be skipped or the other compiled dll added to Test Assets. What do you prefer?

**Comment by MarcoRossignoli** [comment]
I think it's enough to skip update is file system based and should be enough test on one

**Comment by mklemarczyk** [comment]
I found the way to update solution to not limit potential cross-platform usage. I reused previously computed pdb name.

**Comment by mklemarczyk** [comment]
Sorry for the force pushes, I just reduced the impact of this contribution on the code style.

**Comment by mklemarczyk** [comment]
Thank you for the integration :)
@MarcoRossignoli, do you know when is planned next release? It was a while since last one in February.

**Pull request merged**
