### PR TITLE
Fix loss in coverage

### LINKED ISSUE #1037: Double-digit losses of coverage using coverlet.msbuild 3.0.0
In multiple projects' dependabot updates to coverlet.msbuild from 2.9.0 to 3.0.0, there is a double-digit loss of apparent code coverage with zero other changes.

This _seems_ to me like a bug of some kind, rather than a bug fix of aberrant data in a previous release, but if it genuinely is a reflection of true metric misreporting in v2 then fair enough.

Here are links to the generated pull requests and their respective drop in coverage for investigation:

| *PR* | *Coverage Change* |
|:---|:---|
| https://github.com/justeat/JustSaying/pull/846#issuecomment-757635829 | -21% |
| https://github.com/martincostello/alexa-london-travel/pull/444#event-4189005977 | -26% |
| https://github.com/martincostello/alexa-london-travel-site/pull/856#issuecomment-757635443 | -13.44% |
| https://github.com/martincostello/api/pull/539#issuecomment-757634627 | -22.73% |
| https://github.com/martincostello/azure-functions/pull/221#issuecomment-757634789 | -13.38% |
| https://github.com/martincostello/website/pull/686#issuecomment-757635334 | -17.93% |

### PR DESCRIPTION
**Pull request by daveMueller**
closes #1037

### CODE REVIEW

**Comment by daveMueller** [comment]
Mhh I don't have a problem running the integration tests locally. Any idea?

**Comment by JSkimming** [comment]
> Mhh I don't have a problem running the integration tests locally. Any idea?

@daveMueller I think the tests are failing due to this #865 known issue. I get this occasionally, can you trigger a rebuild?

**Comment by MarcoRossignoli** [comment]
> Mhh I don't have a problem running the integration tests locally. Any idea?

Yep sometimes we hit known issue also on our tests for msbuild/.NET Tool

**Review by MarcoRossignoli — APPROVED** [review]
SuperMegaThanks Dave!

**Comment by AraHaan** [comment]
Did this regress again @MarcoRossignoli?

**Comment by MarcoRossignoli** [comment]
Mmm what you mean?for what I know we don't have this issue anymore

**Pull request merged**
