### PR TITLE
TypeLoadException for certain combinations with Microsoft.Extensions.DependencyInjection 6.0.1

### LINKED ISSUE #1390: TypeLoadException error (DependencyInjection) with latest EFCore
Hi,

I noticed that if I upgrade my EF Core libraries to latest (6.0.10), I get an error with coverlet:

```
Data collector 'XPlat code coverage' message: [coverlet]System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollection' from assembly 'Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.GetDefaultServiceCollection(TestPlatformEqtTrace eqtTrace, TestPlatformLogger logger, String testModule)
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.OnSessionStart(Object sender, SessionStartEventArgs sessionStartEventArgs) in /_/src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs:line 132.
```

I'm trying to upgrade Microsoft.EntityFrameworkCore from 6.0.9 to 6.0.10. My project is latest .NET 6.

Is this happening to anyone else? Is there a fix?

### PR DESCRIPTION
**Pull request by daveMueller**
closes #1390

### CODE REVIEW

**Comment by candritzky** [comment]
@daveMueller My expectation was that this would be fixed by lifting the TargetFramework of `coverlet.console.csproj` from `net5.0` to `net6.0`. Maybe it's worth also looking into this.

**Comment by daveMueller** [comment]
Yes I thought about that but the issue also happend for the `coverlet.collector` driver. `coverlet.collector` and `coverlet.core` are both `netstandard2.0`. The collector is totally independent from the global tool and thus it can't be related to `net5.0`.

**Review by petli — APPROVED** [review]
That was a simple fix!

**Comment by cristipufu** [comment]
Thanks for the fix! When can we expect it merged & released?

**Comment by petli** [comment]
I've merged so it should make it into the nightly builds now, at least:
https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Pull request merged**
