### PR TITLE
Empty lines in compiler generated methods

### LINKED ISSUE #799: Improve coverage for edge cases
Take a look at @sharwell comment here https://github.com/dotnet/roslyn-analyzers/pull/3478#issuecomment-609793303

### PR DESCRIPTION
**Pull request by daveMueller**
Partially closes #799

### CODE REVIEW

**Comment by daveMueller** [comment]
Moved the code to skip nested ranges from ```Coverage``` (#1006) to the ```Instrumenter```. Thus I could
omit the empty line from the ```Document```.

**Comment by daveMueller** [comment]
Somebody has an idea what went wrong on the macOS Debug build with the integration test ```Msbuild_SourceLink```?

**Comment by daveMueller** [comment]
Mhh OK this is strange. I just disabled 2 integration tests and enabled them back again and now all tests passed. I also don't have any problems when executing the integration tests locally. I guess we should discuss this when someone finds time to review this. Maybe it has something to do with serialization/deserialization speed because I extended the ```InstrumenterResult``` by a new ```DataMember```.

**Comment by MarcoRossignoli** [comment]
@daveMueller  I need to deeply check...that new prop serialized could be very big, have you compared before and after size to find out some sort of ratio?

**Comment by daveMueller** [comment]
@MarcoRossignoli I now thought of a better solution. I always assumed the documents list is immutable in ```Coverage``` and that's why I made the changes in the ```Instrumenter```.  Just to answer your questions real quick.
1. No changes regarding serialization anymore
2. Avoided to persist it because everything is done in ```Coverage```
3. Yes this was my intention to reuse the data after reloading but this also is obsolete now.

Also thanks for tip with the inprocess debugging.

**Comment by MarcoRossignoli** [comment]
@dave is this PR needed again?

**Comment by daveMueller** [comment]
@MarcoRossignoli I will check this again and get back to you.

**Comment by daveMueller** [comment]
I converted this to draft. I look into it again when I have some more free time.

**Pull request closed without merging**
