### PR TITLE
Align github and nuget release versions

### LINKED ISSUE #1122: Sync nuget and github release versions
Is it possible to sync the github release and the nuget release version?

**Use case**
[renovate](/renovatebot/renovate) is using the github releaes to fetch changelogs for automated dependecy updates.
So currently it can't match a github release to the nuget package version because the version differences.

### LINKED ISSUE #1413: Allign published nuget package version to github release version
As discussed here [https://github.com/coverlet-coverage/coverlet/discussions/1273#discussioncomment-4174929](https://github.com/coverlet-coverage/coverlet/discussions/1273#discussioncomment-4174929) the versions should be synced. 
This was also already discussed in this issue [https://github.com/coverlet-coverage/coverlet/issues/1122](https://github.com/coverlet-coverage/coverlet/issues/1122).

### PR DESCRIPTION
**Pull request by daveMueller**
closes #1122 
closes #1413

### CODE REVIEW

**Comment by daveMueller** [comment]
I'm not sure about how the tag for the github release is created? Even though I change the `AssemblyVersion` in `coverlet.core.csproj` the assembly itself gets the number specified in `version.json`.

grafik

I'm also not really able to see how or if coverlets' azure pipeline is setting the release tag? Doesn't seem so. Is the github release created manually? @MarcoRossignoli @petli 
Then what is the reason for the `AssemblyVersion` in `coverlet.core.cspro` at all? Couldn't we just drop it?

**Comment by MarcoRossignoli** [comment]
> I'm not sure about how the tag for the github release is created?

I'm creating it manually today using the version inside `src/coverlet.core/coverlet.core.csproj`

> I'm also not really able to see how or if coverlets' azure pipeline is setting the release tag?

we're using this workflow to release https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ReleasePlan.md#how-to-manually-release-packages-to-nugetorg with `Nerdbank.GitVersioning`

The nightly is generated using @tonerdo  pipeline and the setup is here https://github.com/coverlet-coverage/coverlet/blob/master/eng/azure-pipelines-nightly.yml

**Comment by daveMueller** [comment]
Thanks @MarcoRossignoli. I think I have everything ready now. I already checked the pipelines and it seems that they also don't use the version in `src/coverlet.core/coverlet.core.csproj`. Thus I think it's safe to just drop it.

**Review by MarcoRossignoli — APPROVED** [review]

**Pull request merged**
