### PR TITLE
Benchmark test

### LINKED ISSUE #1180: Compare coverage of current master build on benchmark project before release
As mentioned in this comment [https://github.com/coverlet-coverage/coverlet/issues/1055#issuecomment-763774694](https://github.com/coverlet-coverage/coverlet/issues/1055#issuecomment-763774694) we want to compare the coverage of the latest coverlet version with the coverage of the current master build on a benchmark project. 

We want to use this as additional test to see changes in the coverage and determine potential bugs that haven't been found by the unit/integration tests before creating a new release.

### PR DESCRIPTION
**Pull request by daveMueller**
closes #1180

### CODE REVIEW

**Comment by daveMueller** [comment]
Using the [refit](https://github.com/reactiveui/refit) projects makes the actions yaml a bit blown up. Maybe someone has a better idea for a benchmark repo that e.g. only has one target framework,... Also currently the action is only triggered manually.

**Comment by MarcoRossignoli** [comment]
I think we can do it manualy @daveMueller like update the guide here https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ReleasePlan.md#how-to-manually-release-packages-to-nugetorg

adding a paragraph with step by step how to compare refit between old and new. I think it's enough I do the release usually so I'll take care to check for "huge" differente.
What do you think?

**Comment by daveMueller** [comment]
> I think we can do it manualy @daveMueller like update the guide here https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ReleasePlan.md#how-to-manually-release-packages-to-nugetorg

I'm cool with it, done.

**Review by MarcoRossignoli — APPROVED** [review]
LGTM

**Pull request merged**
