### PR TITLE
Upgrade Newtonsoft.Json to non-vulnerable version.

### PR DESCRIPTION
**Pull request by josteink**
More details here: https://github.com/advisories/GHSA-5crp-9r3c-p9vr

### CODE REVIEW

**Comment by josteink** [comment]
Uhm. Build still red. Any action needed on my part?

**Comment by josteink** [comment]
From the build:

> /home/vsts/work/1/s/src/coverlet.console/ConsoleTables/ConsoleTable.cs(1,1): error IDE0073: A source file contains a header that does not match the required text [/home/vsts/work/1/s/src/coverlet.msbuild.tasks/coverlet.msbuild.tasks.csproj]

This is clearly not an error in *my* pull-request after all? :smile:

**Comment by josteink** [comment]
"Clearly not" *ahem*

Looking into the errors, and validating on git master, I could see the problem was clearly with my branch.

I've fixed 2 nullability-related issues (which was probably always there) in a couple of tests and it builds and tests cleanly on my machine now :)

**Comment by josteink** [comment]
Build now succeeds, but 1 test now fails in CI (while not locally), and I don't have access to view what test failed or how it failed.

Help? :)

**Comment by Bertk** [comment]
PR is obsolete. The version of Newtonsoft.Json was updated with #1510

**Pull request closed without merging**
